### PR TITLE
Moves legality checker + PRNG

### PR DESCRIPTION
**Pull request by Guernouille**
I have 1564651452614 projects, gonna start somewhere to finish them all right ?
I hope I'm not doing anything wrong.

### CODE REVIEW

**Comment by Guernouille** [comment]
Made a small commit just to be sure I'm doing this the right way.
If everything's fine, I'll add everything from datacrystal I'm 100% sure of in the next commit.

**Comment by iimarckus** [comment]
Thanks. This is really great.

Could you try to make it buildable with [armips](https://github.com/Kingcom/armips/)? Or do you have a preferred N64 assembler? I’m not particularly attached to armips, it’s just the first option I found that was lightweight and sort of worked.

The idea is to build an exact copy of the ROM using disassembled code and chunks of the original ROM where parts haven’t been disassembled yet. This is the method the Game Boy disassemblies (which are now complete, at least Red/Blue and Crystal) used. It serves as a check that there are no typos, and also makes the game easy to edit.

Issues armips has interpreting the code in this commit: it uses 0x instead of $ for hex constants, it doesn’t recognize `mfc0`, and it appears to use different register names. Some or all of these may be bugs in armips that should be fixed. Armips doesn’t support N64 very well yet.

What are you using to disassemble? And what MIPS ABI do you use? I’ve had a hard time figuring out which register names to use when disassembling, and I haven’t found a good N64 debugger either.

Lastly, even though this is a nitpick, please use tabs to indent code and spaces to align comments. Tabs should only be seen at the start of a line, because that way the formatting doesn’t go out of whack if different people have different tab widths (2 spaces, 4, 8, etc.).

**Comment by Guernouille** [comment]
I'm learning how to use CajeASM right now, it probably better suited to n64.
I've changed the $ by 0x and replaced tabs with spaces to align comments. I don't know what armips expects to see to recognize the mfc0 instruction though, so I let it as it is for now.

I use nemu64 and 64DISASM / LemASM to disassemble. There are probably better tools to do this, I'm just used to these.

**Comment by coltongit** [comment]
Can the conflicts here be resolved?

**Comment by ProjectRevoTPP** [comment]
We are on the new build system; it's time to move on.

**Pull request closed without merging**
