### PR TITLE
Setup m2c

### PR DESCRIPTION
**Pull request by Kelebek1**

### CODE REVIEW

**Comment by ProjectRevoTPP** [comment]
What's the point of this PR? What is the need to actually submodule this?

**Comment by Kelebek1** [comment]
To make it easier? Plus the repo has to change libultra to use m2ctx anyway.

**Comment by ProjectRevoTPP** [comment]
What are you talking about? I've already fully integrated libultra.

**Comment by Kelebek1** [comment]
See the ramrom.h change. m2c can't handle sizeof(long) so this needs to change or it'll throw errors.

**Comment by ProjectRevoTPP** [comment]
> See the ramrom.h change. m2c can't handle sizeof(long) so this needs to change or it'll throw errors.

Please explain your use case and what this error is.

**Comment by ProjectRevoTPP** [comment]
Is it still erroring on sizeof long?

**Comment by RevoSucks** [comment]
Closing, stale PR.

**Pull request closed without merging**
